version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_HOST=n8n2.caseebak.com
      - WEBHOOK_URL=https://n8n2.caseebak.com
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
    volumes:
      - n8n-data:/home/node/.n8n
      - ./data:/mnt/data  # LOCAL folder named "data" mapped to /mnt/data inside container

volumes:
  n8n-data:
