version: '3.8'
services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_FUNCTION_ALLOW_EXTERNAL=child_process,fs,os
      - MPLBACKEND=Agg
      - N8N_SECURE_COOKIE=false
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./plots:/tmp/plots  # For saving matplotlib plots
    restart: unless-stopped

volumes:
  n8n_data:
