version: "3.8"

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    volumes:
      - ./data:/home/node/.n8n
      - ./scripts:/data/scripts
      - ./output:/data/chart_output
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
    restart: always
